service: aws-course-bff
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  httpApi:
    cors: true

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    includeModules: true
  autoswagger:
    typefiles: ['./types/product.types.ts', './types/api.types.ts']

functions:
  getProductsList:
    handler: handlers/index.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
          responseData:
            200:
              description: Successful response
              bodyType: ProductList
            500:
              description: Something went wrong
              bodyType: ErrorResponse
  getProductById:
    handler: handlers/index.getProductById
    events:
      - httpApi:
          path: /products/{id}
          method: get
          responseData:
            200:
              description: Successful response
              bodyType: Product
            404:
              description: Product not found
              bodyType: ErrorResponse
            500:
              description: Something went wrong
              bodyType: ErrorResponse
