service: aws-course-bff
frameworkVersion: '3'

useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:*'
    - Effect: Allow
      Action: 'sqs:*'
      Resource:
        - Fn::GetAtt: [catalogItemsQueue, Arn]
    - Effect: Allow
      Action: 'sns:*'
      Resource:
        Ref: createProductTopic

  environment:
    SQS_URL:
      Ref: catalogItemsQueue
    SNS_TOPIC_ARN: !Ref createProductTopic
    NOTIFICATION_EMAIL: ${env:NOTIFICATION_EMAIL}
    NOTIFICATION_EMAIL2: ${env:NOTIFICATION_EMAIL2}

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    includeModules: true
  autoswagger:
    typefiles:
      [
        './types/product.types.ts',
        './types/api.types.ts',
        './types/stock.types.ts',
      ]
  ProductsTable: products
  StocksTable: stocks

functions:
  getProductsList:
    handler: handlers/index.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
          responseData:
            200:
              description: Successful response
              bodyType: ProductList
            500:
              description: Something went wrong
              bodyType: ErrorResponse
  getProductById:
    handler: handlers/index.getProductById
    events:
      - httpApi:
          path: /products/{id}
          method: get
          responseData:
            200:
              description: Successful response
              bodyType: Product
            404:
              description: Product not found
              bodyType: ErrorResponse
            500:
              description: Something went wrong
              bodyType: ErrorResponse
  createProduct:
    handler: handlers/index.createProduct
    events:
      - httpApi:
          path: /products
          method: post
          bodyType: ProductCreate
          request:
            schema:
              application/json: ${file(./schema/createProduct.json)}
              description: 'Validation model for Creating products'
          responseData:
            200:
              description: Successful response
              bodyType: PostProductSuccessResponse
            400:
              description: Product data is invalid
              bodyType: ErrorResponse
            500:
              description: Something went wrong
              bodyType: ErrorResponse
  catalogBatchProcess:
    handler: handlers/index.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - catalogItemsQueue
              - Arn

resources:
  Resources:
    catalogItemsQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'catalogItemsQueue'
    createProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    primeSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${self:provider.environment.NOTIFICATION_EMAIL}
        Protocol: email
        TopicArn: { 'Ref': 'createProductTopic' }
        FilterPolicy:
          price:
            - numeric:
                - '>='
                - 10
    basicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${self:provider.environment.NOTIFICATION_EMAIL2}
        Protocol: email
        TopicArn: { 'Ref': 'createProductTopic' }
        FilterPolicy:
          price:
            - numeric:
                - '<'
                - 10
