// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "import-service",
    "version": "1"
  },
  "paths": {
    "/import": {
      "get": {
        "summary": "importProductsFile",
        "description": "",
        "operationId": "importProductsFile.get./import",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "ServerResponse": {
      "properties": {
        "statusCode": {
          "$ref": "#/definitions/StatusCodes",
          "title": "ServerResponse.statusCode"
        },
        "body": {
          "title": "ServerResponse.body",
          "type": "string"
        }
      },
      "required": [
        "statusCode",
        "body"
      ],
      "additionalProperties": false,
      "title": "ServerResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};